### \#shackspace {#shackspace-irc  .chapter  .big .term}

Die Wortverbindung `#shackspace` (#-Zeichen vorangestellt) zeigt an, dass der IRC-Chat-Kanal gemeint ist.

Dort bleiben shack-e.V.-Mitglieder, -Aktivisten und -Beobachter untereinander in Verbindung und tauschen untereinander Ideen und Informationen aus.

#### Siehe auch:
[Hackerspaces](#hackerspaces)
[Hacker-Ethik](#hacker-ethik)
[shack](#shack)
[shack e.V.](#shack-e-v)

