### CCC {#ccc .chapter .small .term}

Kurzform für [Chaos Computer Club](#chaos-computer-club).

#### Siehe auch:
[Chaos Computer Club](#chaos-computer-club)
[Chaos Computer Club Stuttgart](#chaos-computer-club-stuttgart)

----

