### Girokonto des shack e.V. {#girokonto-des-shack-e.v. .chapter .small .term}

Giro-Konto des shack e.V.:

  ------------- ------------------------
  Inhaber       shack e.V.
  Bank          GLS Gemeinschaftsbank
  BIC           GENODEM1GLS
  IBAN          DE44430609677016809500
  BLZ           43060967
  Kontonummer   7016809500
  ------------- ------------------------

#### Siehe auch:
[shackspace](#shackspace) | 
[shack](#shack) | 
[shack e.V.](#shack-e-v) | 
[Index](#index) | 

----

