### Hacker-Ethik {#hacker-ethik  .chapter  .big .term}

Die Gruppe jener Menschen, die sich selbst stolz als "Hacker" bezeichnen, sind nicht die bösen, üblen Einbrecher in Computer-Netze, als welche sie gerne von Politikern und Medien dargestellt werden.

Der *[Chaos Computer Club](http://www.ccc.de/hackerethics?language=de)* definiert seine Hacker-Ethik wie folgt:

1. Der Zugang zu Computern und allem, was einem zeigen kann, wie diese Welt funktioniert, sollte unbegrenzt und vollständig sein.
1. Alle Informationen müssen frei sein.
1. Mißtraue Autoritäten – fördere Dezentralisierung
1. Beurteile einen Hacker nach dem, was er tut, und nicht nach üblichen Kriterien wie Aussehen, Alter, Rasse, Geschlecht oder gesellschaftlicher Stellung.
1. Man kann mit einem Computer Kunst und Schönheit schaffen.
1. Computer können dein Leben zum Besseren verändern.
1. Mülle nicht in den Daten anderer Leute.
1. Öffentliche Daten nützen, private Daten schützen.

Die "Ethik" des *shack* beschreibt das [Wiki](http://shackspace.de/wiki/doku.php?id=ethik) des [shackspace](#shackspace) wie folgt:

1. Hilf Deinen Mitmenschen; lass Dir helfen.
1. Sprich mit Deinen Mitmenschen; lass mit Dir reden.
1. Räume vor und hinter Dir auf.
1. Leiste einen fairen Beitrag zum Ganzen.
1. Versetze Dich in Dein Gegenüber – Deine Freiheiten enden dort, wo die Deiner Mitmenschen beginnen.
1. Der shack ist weder Deine Wohnung noch ein Hotel.
1. Der shack ist nicht Dein Altgerätelager.



#### Siehe auch:
[Hackerspaces](#hackerspaces)
[Hacker](#hacker)
[shack](#shack)
[shackspace](#shackspace)


----


