### Hacker {#hacker  .chapter  .big .term}

"Hacker" ist die Selbstbezeichnung von Menschen, die kreativ mit Computern, mit Elektronik, mit Technik allgemein und mit ihrer Umgebung insgesamt umgehen.

Hacker versuchen immer, aus vorgefundenem Material das Beste zu machen und auch seine ursprünglichen Funktionen zu übertreffen oder in eine andere Richtung zu lenken.

Im Schwäbischen nennt man Menschen diesen Schlages gerne auch "Tüftler". :-)

Leider versuchen Politik und Medien, die ursprüngliche Bedeutung dieses Wortes ins Gegenteil zu verkehren und dem "Hacken" böswillige, dunkle Ziele zu unterstellen.


#### Siehe auch:
[Hacker-Spaces](#hacker-spaces) | 
[Hacker-Ethik](#hacker-ethik) | 
[shack](#shack) | 
[shackspace](#shackspace) | 



----

