### Hacker-Ethik {#hacker-ethik  .chapter  .big .term}

Die Gruppe jener Menschen, die sich selbst stolz als "Hacker" bezeichnen, sind nicht die bösen, üblen Einbrecher in Computer-Netze, als welche sie gerne von Politikern und Medien dargestellt werden.

Der *[Chaos Computer Club](http://www.ccc.de/hackerethics?language=de)* definiert seine Hacker-Ethik wie folgt:

1. Der Zugang zu Computern und allem, was einem zeigen kann, wie diese Welt funktioniert, sollte unbegrenzt und vollständig sein.
1. Alle Informationen müssen frei sein.
1. Mißtraue Autoritäten – fördere Dezentralisierung
1. Beurteile einen Hacker nach dem, was er tut, und nicht nach üblichen Kriterien wie Aussehen, Alter, Rasse, Geschlecht oder gesellschaftlicher Stellung.
1. Man kann mit einem Computer Kunst und Schönheit schaffen.
1. Computer können dein Leben zum Besseren verändern.
1. Mülle nicht in den Daten anderer Leute.
1. Öffentliche Daten nützen, private Daten schützen.

Siehe auch [shack-Grundsätze](#shack-grundsaetze).


#### Siehe auch:
[Hacker-Spaces](#hacker-spaces) | 
[Hacker](#hacker) | 
[shack](#shack) | 
[shackspace](#shackspace) | 
[shack-Grundsätze](#shack-grundsaetze) | 


----


