### Hacker-Spaces {#hacker-spaces .chapter .big .term}

Hacker-Spaces sind Clubhäuser und Räumlichkeiten, in denen sich Nerds, Computer-Anwender, Programmierer, Elektronik-, Holz-, Metall-Bastler und andere Kreative treffen und ihren Projekten und Interessen nachgehen.

Sie sind der natürliche Lebensraum von Menschen aller Geschlechter, die kritisch, aktiv, "eigen", tolerant, neugierig, kreativ, erfinderisch, schwierig, intelligent und nachtaktiv sind.

Weltweit gibt es hunderte dieser digitalen Bastlerzentren. In Stuttgart ist das der [shackspace](#shackspace).

Sie sind locker untereinander verbunden und pflegen freundschaftlichen Austausch von Ideen quer über alle Grenzen.

Ein (fast) vollständige Liste von Hacker-Spaces findet sich hier:

* **[http://hackerspaces.org/wiki/List_of_Hacker_Spaces](http://hackerspaces.org/wiki/List_of_Hacker_Spaces)**

Jeder Hacker-Space ist anders -- aber jeder einzelne ist ein dreigeteiltes soziales Experiment.
Denn...

1. ...er ist ein Raum, wo man auf einer 24/7-Basis an digitalen Projekten arbeiten kann.
   Wo Lötkolben brutzeln und Kabel auf Platinen treffen, um Roboter zu erschaffen.
   ***Also eine Werkstatt.***

2. ...ist ein Hacker-Space ein Ort, wo sich Gruppen treffen können.
   Um dort zu lernen, sich auszutauschen, sich digital fortzubilden.
   ***Also ein Platz des Lernens.***

3. ...ist er wegen der die beiden vorherigen Anliegen eine Örtlichkeit mit Infrastruktur (Sofa, Getränke, Kochgelegenheit,...), die rund um die Uhr unterstützt und Platz gibt für Neuigkeiten, Austausch und Geschichten.
   ***Also ist ein Hacker-Space auch ein Treffpunkt.***

Dieses dreigeteilte Funktions-Spektrum hat sich als globales Erfolgsmodell erwiesen.
Sörfe rüber zur [Liste von hackerspaces.org](http://hackerspaces.org/wiki/List_of_Hacker_Spaces).
Dort erfährst du von über 400 Ablegern zwischen Sydney, Kalkutta, Kapstadt und Stuttgart-Wangen.
Wo seit 2 Jahren der Stuttgarter Hacker-Space "[shack](#shack)" ansiedelte.
Aber worin ähneln sich diese Räume und was unterscheidet sie?

Gleich ist für alle, dass diese Räume durch die Nutzer selbst verwaltet und organisiert sind.
Und alle haben einen Schwerpunkt auf dem furchtlosen Angriff auf Hard- und Software, also der Zähmung des digitalen Erlebens.
Wobei diese Zähmung sehr unterschiedlich ausfallen kann:

* im österreichischen Wörgl kann man im '[Zeitsparwerk](http://hackerspaces.org/wiki/Zeitsparwerk)' auch Krafttraining machen;
* in [Novi Sad](http://www.ns-linux.org/) dagegen liegt der Schwerpunkt mehr auf Linux;
* in Berlin ist die '[c-base](http://www.c-base.org/)' für abgefahrene Parties berühmt;
* die '[garagegeeks](http://www.garagegeeks.org/index.html)' in Israel arbeiten an *'Converting a real skateboard into a game controller'*.

Und so geht es global heiter weiter...

Den Unterschied machen jeweils die Menschen, die an jedem Ort den Hacker-Space mit ihren Projekten, ihrer Begeisterung und finanziellem Einsatz formen.
So ist kein Space wie der andere.
Denn es gibt keinerlei festen Regeln und Vorgaben, wie man einen Space aufbaut.

Allerdings gibt es ein legendär direkt-subversives PDF, das viele weltweit angesteckt hat, einen eigenen Space zu eröffnen:

* **[Building a Hackerspace](http://events.ccc.de/congress/2007/Fahrplan/attachments/1003_Building%20a%20Hacker%20Space.pdf)** (von *Lars Weiler* und *Jens Ohlig*)

Lade Dir dieses Dokument herunter, lies es und Du wirst verstehen, worum es bei einem Hacker-Space wirklich geht.


#### Siehe auch:
[Hacker](#hacker) | 
[Hacker-Ethik](#hacker-ethik) | 
[Hacker-Spaces](#hacker-spaces) | 
[shack](#shack) | 
[shackspace](#shackspace) | 
[shack e.V](#shack-e-v) | 


----

