### "Hinter'm Kühlschrank" (Regal) {#hinterm-kuehlschrank .chapter .small .term}

Das Regal mit dem schönen Namen "Hinter'm Kühlschrank" befindet sich im [Lagerraum](#lagerraum). Es ist unverwechselbar beschriftet.


#### Siehe auch:
[Handtücher](#handtuecher)
["Hinter'm Kühlschrank" (Regal)](#hinterm-kuehlschrank)
[Toilettenpaper](#toilettenpapier)
[Lagerraum](#lagerraum)
[Wäschekorb](#waeschekorb)

