### Key-Member {#key-member .chapter .small .term}

Auf Deutsch: Schlüssel-Besitzer.

 ![Fortschrittsbalken shackspace-Glossar](../images/glossary-progress.png "Fortschrittsbalken shackspace-Glossar")  Hier fehlt noch DEIN Beitrag. Hier fehlt noch DEIN Beitrag.  Hier fehlt noch DEIN Beitrag. Hier fehlt noch DEIN Beitrag.  Hier fehlt noch DEIN Beitrag. Hier fehlt noch DEIN Beitrag.  Hier fehlt noch DEIN Beitrag.

#### Siehe auch:
[Key](#key) | 
[Key-Holder](#key-holder) | 
[Key-Request](#key-request) | 
[Key-Übergabe](#key-uebergabe) | 
[Portal](#portal) | 
[Index](#index) | 

----

