### Key-Übergabe {#key-uebergabe .chapter .small .term}

Im shack gibt es immer ein *Key-Member*, welches den Status *"Key-Holder"* hat.
Verläßt diese Person den shack, so muss...

* ...entweder der Key an ein anderes Key-Member übergeben werden, 
* ...oder alle anderen Besucher müssen den shack verlassen.

Das Vorgehen zum Key-Transfer ist folgendes: 

1. Das aktuelle Key-Member kann seinen KeyHolder-Status an ein anderes anwesendes Key-Member übergeben.
1. Der neue Key-Holder muss sich am Portal einloggen.

Damit ist dann dokumentiert/bewiesen, dass der Key-Holder-Status an ein anderes Key-Member übergegangen ist.


#### Siehe auch:
[Key](#key) | 
[Key-Holder](#key-holder) | 
[Key-Member](#key-member) | 
[Key-Request](#key-request) | 
[Portal](#portal) | 

----

