### Label-System {#label-system .chapter .small .term}

Equipment, Werkzeug und Verbrauchsmaterial im Shack ist nicht alles im Vereins-Besitz.
Viele Gegenstände sind Privat-Besitz.

Daher sind Equipment, Werkzeug und Verbrauchsmaterial im Shack so zu labeln, dass `${Leute}´ wissen, was man damit machen darf und/oder wen sie um Erlaubnis fragen müssen.
Wir haben ein Kennzeichnungs-System entwickelt, welches die Nutzungs-Regeln des jeweiligen Gegenstands beschreibt.

Es gibt 5 verschiedene Sticker im DIN-A8-Format.
Sie sind einheitlich gestaltet, farblich gekennzeichnet und stellen verbindlich dar, wie `${SACHE}` zu benutzen ist.

Quellen der Sticker finden sich hier:

* [https://github.com/shackspace/corporate-identity/tree/master/access-policy-sticker](https://github.com/shackspace/corporate-identity/tree/master/access-policy-sticker)

  Label        Farbe       Bedeutung
  ------------ ----------- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  OWNER ONLY   rot         Nur mit ausdrücklicher Genehmigung des Eigentümers benutzen/verbrauchen
  INSTRUCTED   rot/gelb    Nur mit Einweisung benutzen/verbrauchen [(Link zu Formular zum Ausdrucken)](https://docs.google.com/spreadsheets/d/1IYX0mAL2n3CopRQXWReUlPScJa94NMLHUaD2r3OUXvE/edit#gid=0)
  DOCUMENTED   gelb        Nur nach Anleitung verwenden
  GIVE AWAY    grün/weiß   Zum Mitnehmen
  PUBLIC       grün        Nutzung für alle erlaubt

![So sehen die (neuen) Farb-Labels aus...](../images/shack-labels.png)

**Ältere Regelungen**

Es gibt ältere Kennzeichnungen. Diese haben folgende Bedeutungen:

* ***"public" handschriftlich*** --- Nutzung für alle erlaubt.
* ***Name o. Nick o. Email-Adresse angegeben*** --- Privatkram, Finger weg.
* ***Name o. Nick o. Email-Adresse angegeben und "public" handschriftlich*** --- Privateigentum, zur Benutzung fuer alle.
* ***"shack" handschriftlich*** --- Vereinseigentum, zur Benutzung fuer alle.
* ***etwa daumengrosse weisse Label mit runden Ecken und shacklogo*** - Vereinseigentum, zur Benutzung fuer alle (einige wenige davon sind auf privaten Laptops gelandet *sigh*).
  *Anmerkung: die kleinen weißen Sticker waren nie wirklich als Device-Label gedacht, wurden aber als solche verwendet ;) --- so oder so ist es widersprüchlich.*
* ***grobes Malerkrepp mit 4-stelligen Nummern*** --- ([hier dokumentiert](http://shackspace.de/wiki/doku.php?id=aufraeumen))

#### Siehe auch:
[Eigentum](#eigentum) | 
[Eigentums-Sticker](#eigentums-sticker) | 
[Einweisung](#einweisung) | 
[Equipment-Label-System](#equipment-label-system) | 
[Geräte-Einweisung](#geraete-einweisung) | 
[Kennzeichnungs-System](#kennzeichnungs-system) | 
[Index](#index) | 

----

