### MPD {#mpd .chapter .small .term}

Kurzform für [Music Player Daemon](#music-player-daemon)

#### Siehe auch:
[Musik](#musik) ] | 
[Music Player Daemon](#music-player-daemon) | 
[Musik-Server](#musik-server) | 
[Index](#index) | 

----

