### Musik-Server {#musik-server .chapter .small .term}

Deutsche Bezeichnung für [Music Player Daemon](#music-player-daemon).

#### Siehe auch:
[MPD](#mpd) | 
[Music Player Daemon](#music-player-daemon) | 
[Musik](#music) | 

----

