### Rote Steckdosen {#rote-steckdosen .chapter .small .term}

Die *roten* Steckdosen in den Räumlichkeiten des shack bleiben über Nacht am Strom.
Andere Steckdosen werden nach erfolgtem [Shutdown](#shutdown) stromlos.

#### Siehe auch:
[Shutdown](#shutdown) | 
[]() | 
[]() | 
[Index](#index) | 

----

