### shack-Grundsätze {#shack-grundsaetze .chapter .small .term}

1. Hilf Deinen Mitmenschen; lass Dir helfen.
1. Sprich mit Deinen Mitmenschen; lass mit Dir reden.
1. Räume vor und hinter Dir auf.
1. Leiste einen fairen Beitrag zum Ganzen.
1. Versetze Dich in Dein Gegenüber -– Deine Freiheiten enden dort, wo die Deiner Mitmenschen beginnen.
1. Der shack ist weder Deine Wohnung noch ein Hotel.
1. Der shack ist nicht Dein Altgerätelager.

Konkretisierungen

* Kein Hacken der anderen Mitreisenden oder Picken von in Betrieb befindlichen Schlössern ohne explizite Genehmigung (5).
* Maximale Lautstärke ist die niedrigste, die von allen Anwesenden toleriert wird (2, 5).
* Respektiere fremdes [Eigentum](#eigentum) (5).
* Respektiere Eigentum/Werkzeug (Siehe [Kennzeichnungs-System](#kennzeichnungs-system)) (5).
* Länger im shack befindliche Gegenstände sollten mit Namen des Besitzers und eventuell "public" markiert werden.
* Herumliegende Sachen ohne Markierung oder mit "public" können benutzt werden (4), werden aber pfleglich behandelt, nicht zerstört (5) und hinterher dahin zurück geräumt, wo sie herkamen (3).
* Bei Bild- und Tonaufnahmen sind das Persönlichkeitsrecht und das Recht der Abgebildeten am eigenen Bild zu beachten (5).
* Die Küche ist in jedem Fall hygienisch zu hinterlassen (3, 4).
* Verdorbenes im Kühlschrank ist zu entsorgen (3, 4).
* Toiletten sind in einem hygienischen und betriebsbereiten Zustand zu verlassen (4, 5).
* Gib Änderungen an der Infrastruktur auf der Mailingliste bekannt (5).
* Wenn du ansteckend krank bist, bleib bitte zu Hause, damit nicht andere Leute angesteckt werden. (5).
* Es gilt absolutes [Rauch-Verbot](#rauch-verbot) in allen Räumen.
* Illegale [Drogen](#drogen) sind immer, harter [Alkohol](#alkohol) ausserhalb von angemeldeten Partys verboten.
* Körperliche Auseinandersetzungen führen zum sofortigen [Hausverbot](#hausverbot) für alle Beteiligten; über Aufhebung des Hausverbots entscheidet das Plenum; die Beteiligten haben dort die Gelegenheit, sich zu äußern.



#### Siehe auch:
[Ethik](#ethik) | 
[Hacker](#hacker) | 
[Hacker-Ethik](#hacker-ethik) | 

----

