### shack e.V. {#shack-e-v  .chapter  .big .term}

23 (!) Menschen haben am 20.02.2010 den Verein "shack e.V" gegründet.

Der gewählte  Namen ist die ultimativ kurze Verbindung aus 'Stuttgart' und 'Hackerspace', also: shack.

Ausreichende Betriebsräume hat der shack e.V. seit April 2011 in der Ulmer Strasse 255 in Stuttgart-Wangen:
über 350qm, mitsamt Küche, Seminarraum, Medienlabor, Lounge, Elektrowerkstatt, Werkstatt fürs Grobe und Rechenzentrum –- ein Platz, um Projekte wahr zu machen und furchtlose Digitalkultur zu leben.

Inzwischen ist die Mitgliederzahl auf circa 210 angewachsen.

Der shack e.V. ist anerkannt als gemeinnützig.
Er verfolgt keinerlei (partei)politische Ziele.

Neben dem Betrieb des shackspace ist er auch stark im Bereich der Jugend- und Erwachsenenbildung engagiert.


#### Siehe auch:
[Hackerspaces](#hackerspaces)
[Hacker-Ethik](#hacker-ethik)
[shack](#shack)
[shackspace](#shackspace)

