### shack in Sozialen Medien {#shack-soziale-medien .chapter .small .term}

  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Medium                      Link                                                                                  Kommentar
  --------------------------- ------------------------------------------------------------------------------------ ------------------------------------------------------------------------------------
  Mailingliste                <public@lists.shackspace.de>                                                          Anmelden über das
                                                                                                                    [Webinterface](https://lists.shackspace.de/mailman/listinfo/public "https://lists
                                                                                                                    .shackspace.de/mailman/listinfo/public") möglich

  Twitter                     @[shackspace](https://twitter.com/shackspace "https://twitter.com/shackspace"),
                              @[shackspam](https://twitter.com/shackspam "https://twitter.com/shackspam")

  Website                     [shackspace.de](http://www.shackspace.de "http://www.shackspace.de")

  Wiki                        [start](/wiki/doku.php?id=start "start")

  YouTube                     [shackev](http://www.youtube.com/user/shackev "http://www.youtube.com/user/shackev")

  Vimeo                       [shackspace](http://vimeo.com/shackspace "http://vimeo.com/shackspace")             
  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#### Siehe auch:
[]() | 
[]() | 
[]() | 
[Index](#index) | 

----

