### shackspace {#shackspace  .chapter  .small .term}

"shackspace" (Kurzform: "shack") ist der offizielle Name der Räume des Stuttgarter Hacker-Spaces, den der Verein *["shack e.V."](#shack-e-v)* betreibt.

"shack" oder "shackspace" sind immer klein zu schreiben, selbst zu Beginn eines Satzes.

Der shackspace ist eine offene Werkstatt für menschenfreundliche Computerkultur mit Programmierung und Ergebnistoleranz.

Mit über 350qm, mitsamt Küche, Seminarraum, Medienlabor, Lounge, Elektrowerkstatt, Werkstatt fürs Grobe und Rechenzentrum ist der shack eine coole Location, um Projekte wahr zu machen und furchtlose Digitalkultur zu leben.

Internet-Adresse:

* **[http://shackspace.de/](http://shackspace.de/)**

Geografische Adresse:

> | shackspace
> | Ulmer Straße 255
> | D-70327 Stuttgart (Wangen)
> | Haltestelle "Im Degen" (U4/U9)

***Bitte keine Post & keine Pakete/Päckchen an diese Adresse schicken! (Kommt nicht an.)**

#### Siehe auch:
[Hacker-Spaces](#hacker-spaces) | 
[Hacker-Ethik](#hacker-ethik) | 
[shack](#shack) | 
[shack e.V.](#shack-e-v) | 
[Index](#index) | 

----

