### shack-Vorstand {#shack-vorstand .chapter .small .term}

Den shack-Vorstand erreichst Du unter <<vorstand@shackspace.de>>.

Die folgenden Leute bilden momentan den Vorstand:

  ---------------------------------------------------------------------------------------------------------------------------------------------------
                      Name                           Mail                                       Twitter
  ------------------- ------------------------------ ------------------------------------------ -----------------------------------------------------
  1\. Vorstand        Jan Vanvinkenroye                                                         @[jvanvinkenroye](https://twitter.com/jvanvinkenroye 
                                                                                                "https://twitter.com/jvanvinkenroye")

  Kassenwart          David Mändlen                                                             @[Laird\_Dave](https://twitter.com/Laird_Dave 
                                                                                                "https://twitter.com/Laird_Dave")

  Schriftführer       hadez                          hadez /at/ c-base /dot/ org                @[hdznrrd](https://twitter.com/hdznrrd 
                                                                                                "https://twitter.com/hdznrrd")

  1\. Beisitzer       momo                                                                      @[momorientes](https://twitter.com/momorientes 
                                                                                                "https://twitter.com/momorientes")

  2\. Beisitzer       h0uz3                                                                     @[h0uz3](https://twitter.com/h0uz3 
                                                                                                "https://twitter.com/h0uz3")
  ---------------------------------------------------------------------------------------------------------------------------------------------------

#### Siehe auch:
[]() | 
[]() | 
[]() | 
[Index](#index) | 

----

