### SHS {#shs .chapter .small .term}

Kurz-Bezeichnung für [Saturday Hack Sessions](#saturday-hack-sessions).

#### Siehe auch:
[Saturday Hack Sessions](#saturday-hack-sessions) | 
[Index](#index) | 

----

