### Shutdown {#shutdown .chapter .small .term}

1. Etwaig anwesenden Personen die Durchführung des Shutdowns bekanntgeben.
1. Geschirrspülmaschine starten, wenn sie halbwegs voll ist.
1. Kontrollieren, ob Herd aus ist.
1. :!: Bastel-Equipment ausschalten und ausstecken (z.B. Lötkolben)!
1. :!: Alle Fenster schließen! (Ausnahme Serverraum)
1. Anwesende Nichtmitglieder werden höflich gebeten, aufgrund des Shutdowns die Räumlichkeiten zu verlassen.
1. Bei Missachtung wird das [Hausrecht ausgeübt](#hausrecht).
1. Lichtquellen ausschalten (Lichtschalter für die Lounge ist ~~das Breadboard das~~ die Platine, welche neben dem Lichtverteiler in der Lounge hängt).
1. Hauptschalter am Lichtverteiler in der Lounge von I auf O umlegen.
    i. Zur Zeit ist dieser Hauptschalter in der Lounge "in function" ~~"out of function"~~.
    i. ~~Im hinteren Sicherungskasten die beschriftete Sicherung neben dem Netzschütz umlegen~~.
        * Zur Info: Es gibt quasi 2 Overides um die Eltako-Ansteuerung des Netzschützes zu übersteuern:
            a. Manuell einschalten: Der eine Override neben dem Netzschütz ist parallel zum Schließerkontakt des Eltako-Aktors.
            a. Manuell ausschalten: Sicherung Nr. 12 ist die Sicherung des Netzschützes.
                Mit dieser Sicherung wird der Stromkreis der Spule vom Netzschütz getrennt.
                Wenn noch mehr spinnt und der vorherige Schritt nicht helfen sollte, dann noch Sicherung Nr. 11 ausschalten.
                Wenn manuell ausgeschaltet wird, kann auch nicht vom Eltako( Steuerung) eingeschaltet werden.
1. :!: Strom in den [Options-Räumen](#options-raum) abstellen.
   Im [Sicherungs-Kasten](#sicherungs-kasten) im [OR1](#or1) links oben befinden sich 4 Schalter (Sicherungen).
    i. Durchlauferhitzer [Dusche](#dusche)
    i. Durchlauferhitzer [E-Lab](#e-lab) (noch nicht verwenden!)
    i. [Options-Räume](#options-raum)
    i. [Küche](#kueche)
    i. Der Strom für die Küche bleibt noch 90 Minuten eingeschaltet.
    i. Der Strom wird automatisch über den Hauptschalter in der [Lounge](#lounge) deaktiviert.
       Falls dies nicht funktioniert, kann über die Sicherung F06 der Steuerstrom für das Eltako-Relais und die 4 Schütze deaktiviert werden.
       Selektiv kann auch die Vorsicherung des entsprechenden Bereiches deaktiviert werden. (Siehe Dokumentation vor Ort)
1. Raum abschließen.
1. Dazu einen [Portal Close](#portal-close) durchführen oder alternativ an der roten Box neben der Tür den Knopf an der rechten Seite drücken und den Raum innerhalb von 15-20 sec. verlassen.
1. :!: Abschließend physikalisch überprüfen, ob die Tür wirklich verriegelt ist.
1. HW-Key bleibt im [shackspace (keyboard)](#keyboard) und kann von [Key-Membern](#key-member) mitgenommen werden, wenn diese am nächsten Tag als erste wieder da sein wollen/sind.
    Diese Aktion ist auf key@ entsprechen zu dokumentieren.
1. :!: Bitte sicherstellen, dass die Heizkörper aus sind! (Stufe 1 == „aus“).

#### Siehe auch:
[shackspace](#shackspace) | 
[Startup](#startup) | 
[Index](#index) | 

----

