### Spül-Maschine {#spuel-maschine .chapter .small .term}

In Betriebs-Zustand versetzen: 

- Tab unter der Spüle rausnehmen.
- Tab in die Spül-Maschine in das entsprechend dafür vorgesehene Fach verfrachten. 
- Klappe schließen. 
- Am Rad im Uhrzeigersinn auf die Stufe 2 drehen.
- Maschine einschalten. 
- Falls sie nicht losläuft: von Hand am Rad auf kurz nach zwei drehen. Sie sollte dann automatisch anlaufen.

#### Siehe auch:
[]() | 
[]() | 
[]() | 
[Index](#index) | 

----

