### Startup {#startup .chapter .small .term}

Um den [shackspace](#shackspace) in Betriebszustand zu versetzen, muss das aufschliessende [Key-Member](#key-member) folgende Start-Up-Prozedur durchführen:

1. Raum [aufschliessen](#aufschliessen).
1. ~~Im Hauptunterverteiler hinten in der Werkstatt die Sicherung mit der Bezeichnung *'shutdown'* (neben Netzschütz) reinmachen.~~
1. Hauptschalter neben Lichtverteiler in der Lounge auf 1 drehen.
1. Lichtquellen bei Bedarf einschalten.
1. Temperatur im Serverraum kontrollieren.
   Eventuell Lüfter ans offene Fenster stellen und kalte Luft reinblasen.
1. Die ganze IT läuft durch und ist sofort verfügbar.
1. :!: Strom in den Options-Räumen wird automatisch mit dem Hauptschalter in der Lounge mit eingeschaltet.
   ~~Strom in Options-Räumen und Küche nach Bedarf einschalten.~~
   Im Sicherungskasten im OR1 links Oben befinden sich 4 Schalter (Sicherungen).
    1. Durchlauferhitzer Dusche
    2. Durchlauferhitzer E-Lab (noch nicht verwenden!)
    3. Options-Räume
    4. Küche
1. ~~Wird der Hebel nach oben bewegt, wird der entsprechende Stromkreis aktiviert.~~
   Mit diesen Schaltern kann man einen Override aktivieren.
   Allerdings kann man dann nicht mehr per Hauptschalter in der Lounge ausschalten.

#### Siehe auch:
[Aufschliessen](#aufschliessen) | 
[Key-Holder](#key-holder) | 
[Key-Member](#key-member) | 
[Shutdown](#shutdown) | 
[shackspace](#shackspace) | 
[Index](#index) | 

----

