### Workshop Python {#workshop-python .chapter .small .term}

Der Python-Workshop im shackspace trifft sich seit geraumer Zeit regelmäßig:
und zwar alle zwei Wochen, Freitags ab 19 Uhr.

Der Workshop richtet sich an alle Erfahrungsstufen. Sowohl für blutige Anfänger als auch für gesottene Veteranen und Umsteiger ist etwas dabei.

Weitere Informationen:

* [Google+ Community](https://plus.google.com/communities/104664589088135148756)



#### Siehe auch:
[Workshops](#workshops) | 
[Index](#index) | 

----

