### Workshops {#workshops .chapter .small .term}

Der shackspace ist Gastgeber für mehrere (externe) Gruppen, die sich hier regel- oder auch unregelmäßig treffen, um Workshops, Seminare und Diskussionsabende abzuhalten.

Dazu gehören:

1. [Workshop Cypherpunks](#workshop-cypherpunks)
1. [Workshop Python](#workshop-python)

#### Siehe auch:
[Workshop Cypherpunks](#workshop-cypherpunks) | 
[Workshop Python](#workshop-python) | 
[Index](#index) | 

----

